modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="installer"
version="1.0.0"
displayName="Installer"
displayURL="https://discord.gg/JjRmg8e4tR"
credits="WereF0X"
authors="WereF0X"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.installer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"